### ISSUE TITLE
unrecognized token: "["

### ISSUE THREAD

**Issue by bsilverm** [dinedal/textql#100]
Every now and then I get the following error when parsing my logs:

2018/07/13 13:26:10 unrecognized token: "["

I was able to find a sample line that always seems to generate the error.  I've attached a file that contains a sample problem line with the header I'm using.

This is the command I use and the result:

textql -save-to "test/db/mydb.db" -header -dlm=0x7c -sql "count()" test/log
2018/07/13 13:35:33 unrecognized token: "["

[repro.txt](https://github.com/dinedal/textql/files/2193645/repro.txt)

Any ideas on where this error comes from?  Thanks,

**Comment by dinedal** [comment]
Thank you for submitting a reproducible issue! I appreciate it.

I will investigate and fix this issue, it is probably a bug; sorry about that!

**Comment by dinedal** [comment]
Please do! I am busy with the day job sadly

**Comment by billtsalamander** [comment]
I'm getting the issue, though maybe a different bug with the same symptom. The strangest part is that it depends on the way I do the path.
Steps to reproduct
cat b.csv
a, b, c
1, 2, 0

textql -header -sql  " select q.* from b as q "  ./ 
2018/08/03 13:00:45 unrecognized token: "["

textql -header -sql  " select q.* from b as q "  b.csv
1,2,0

**Comment by bsilverm** [comment]
Any leads on this one?  Thanks!
