### ISSUE TITLE
Add an AUR package for textql

### ISSUE THREAD

**Issue by dessalines** [dinedal/textql#102]

**Comment by dinedal** [comment]
What's AUR?

**Comment by dessalines** [comment]
The [Arch User Repository](https://aur.archlinux.org/), a streamlined method for installing applications.

**Comment by Aniket-Pradhan** [comment]
Hey @dinedal 

I can help you in uploading the package to AUR. You basically need to make a PKGBUILD file. You can study more about it [here](https://wiki.archlinux.org/index.php/creating_packages).

Do you mind, if I take up this issue and make publish it to AUR?

**Comment by dinedal** [comment]
Please feel free.

**Comment by Aniket-Pradhan** [comment]
Thanks for the opportunity. I will get back to you soon, as I am quite busy this week.

**Comment by Aniket-Pradhan** [comment]
Hey!!

I have created an aur package, [here](https://aur.archlinux.org/packages/textql-git/). Please have a look at it.

You can install it by using your favorite aur-helper, or build it your self.

I used the `go get` in the `PKGBUILD`, so it's easier to maintain the package from git only. @dinedal , if you want, I can add you as a maintainer as well. I have also quoted you on the PKGBUILD, for this amazing tool. :)

I'll soon submit a pull request to add the PKGBUILD to the git repo and some instructions in the readme to help the aur users install this package.

**Comment by dinedal** [comment]
Sorry for the long wait here, this is merged
