### ISSUE TITLE
Semicolon in literal breaks the processing

### ISSUE THREAD

**Issue by v-from-meiro** [dinedal/textql#125]
Hi!

We found a problem while passing SQL query with semicolon in literal. 

Way to reproduce:

`textql -sql "select 'some text with ; semicolon' || ' another text' "`

Expected behavior is that it shows text:

`'some text with ; semicolon another text'`

But instead, we get error:
`2020/06/05 10:12:36 unrecognized token: "'some text with "`

Let me know in case of question or how we can help! We are python-oriented company, so going into Go is not really in our powers right now :/

**Comment by dinedal** [comment]
Yes, this is a bug :) I'll see what I can do.

**Comment by dinedal** [comment]
Thanks to #132
