### ISSUE TITLE
Improved Table Display

### ISSUE THREAD

**Issue by olekukonko** [dinedal/textql#13]
I think you can improve display of elements by using [tabwriter](http://golang.org/pkg/text/tabwriter/) or preferably [tablewriter](https://github.com/olekukonko/tablewriter)

What do you think ?

**Comment by dinedal** [comment]
Sorry @olekukonko it took so long... but: https://github.com/dinedal/textql/commit/1539f62f06c19ceaa0e96acc672e9ba946ee2873

Thanks for making tablewriter!
