### ISSUE TITLE
Will it work on a Windows machine?

### ISSUE THREAD

**Issue by ArthurZ** [dinedal/textql#18]
I guess it must work on a Linux machine as Ubuntu, but

Will it work on a Windows machine?

**Comment by superurbi** [comment]
Is there any documentation to setup textql in Windows?
I'm a newbie with textql. 
thanks!

**Comment by dinedal** [comment]
You'll need to install it as a normal Go program.

I don't know how Go works on Windows, so I can't offer much support here :(
