### ISSUE TITLE
seems interesting, but ... 

### ISSUE THREAD

**Issue by kannan83** [dinedal/textql#19]
it's very interesting doing sql like query on simple csv/tsv files but it would be more interesting if it can be done *WITHOUT*  having a sql database behind there. 

what i would like is to get rid of having dependencies towards any sql database but still accepting sql like queries . so the idea is to serve queries by interpreting sql on the fly...
for example, having an embedded sql interpreter engine for sql like queries, xquery interpreter engine for xquery like queries ... etc.

**Comment by dinedal** [comment]
Thank you, I have made textql very modular in the latest release, but I have not gotten to other kinds of queries for the moment.
