### ISSUE TITLE
Joins over two files

### ISSUE THREAD

**Issue by tlehman** [dinedal/textql#20]
First of all, textql is awesome!

I haven't been able to figure out how to do a JOIN in a single command (if that's even possible), as a concrete example I have two TSV files, one for child mortality by country and another for GDP by country:

```
→ ls
mort.tsv  gdp.tsv
```

I can do queries over each file, sorting, selecting, limiting, etc.

```
→ textql -dlm=tab -header=false -source=gdp.tsv -sql='select c1, c0 from tbl order by cast(replace(c1,",","") as integer) desc LIMIT 5'
16,244,600,000,000, United States
8,227,102,629,831, China
5,959,718,262,199, Japan
3,428,130,624,839, Germany
2,612,878,387,760, France
```

What I would like to do is an inner join on the two files on the country column.

From looking at the source code, I see that there is one `table_name` variable, does this mean that only one table is supported?

**Comment by dinedal** [comment]
Released as part of V2!

**Comment by tlehman** [comment]
:+1:
