### ISSUE TITLE
I can't seem to install it?

### ISSUE THREAD

**Issue by solidismail** [dinedal/textql#33]
help
i use : 

GO :  go1.2.2.darwin-amd64-osx10.8.tar.gz
OS : Darwin MAC-ISMAIL.local 13.2.0 Darwin Kernel Version 13.2.0: Thu Apr 17 23:03:13 PDT 2014; root:xnu-2422.100.13~1/RELEASE_X86_64 x86_64

i.sebbane in ~
☢ go get -u github.com/dinedal/textql
package github.com/dinedal/textql
	imports bytes: unrecognized import path "bytes"
package github.com/dinedal/textql
	imports database/sql: unrecognized import path "database/sql"
package github.com/dinedal/textql
	imports database/sql/driver: unrecognized import path "database/sql/driver"
package github.com/dinedal/textql
	imports encoding/csv: unrecognized import path "encoding/csv"
package github.com/dinedal/textql
	imports encoding/hex: unrecognized import path "encoding/hex"
package github.com/dinedal/textql
	imports errors: unrecognized import path "errors"
package github.com/dinedal/textql
	imports flag: unrecognized import path "flag"
package github.com/dinedal/textql
	imports fmt: unrecognized import path "fmt"
package github.com/dinedal/textql
	imports github.com/mattn/go-sqlite3
	imports io: unrecognized import path "io"
package github.com/dinedal/textql
	imports github.com/mattn/go-sqlite3
	imports runtime: unrecognized import path "runtime"
package github.com/dinedal/textql
	imports github.com/mattn/go-sqlite3
	imports runtime/cgo: unrecognized import path "runtime/cgo"
package github.com/dinedal/textql
	imports github.com/mattn/go-sqlite3
	imports strings: unrecognized import path "strings"
package github.com/dinedal/textql
	imports github.com/mattn/go-sqlite3
	imports syscall: unrecognized import path "syscall"
package github.com/dinedal/textql
	imports github.com/mattn/go-sqlite3
	imports time: unrecognized import path "time"
package github.com/dinedal/textql
	imports github.com/mattn/go-sqlite3
	imports unsafe: unrecognized import path "unsafe"
package github.com/dinedal/textql
	imports github.com/mattn/go-sqlite3
	imports io/ioutil: unrecognized import path "io/ioutil"
package github.com/dinedal/textql
	imports github.com/mattn/go-sqlite3
	imports log: unrecognized import path "log"
package github.com/dinedal/textql
	imports github.com/mattn/go-sqlite3
	imports os: unrecognized import path "os"
package github.com/dinedal/textql
	imports github.com/mattn/go-sqlite3
	imports os/exec: unrecognized import path "os/exec"
package github.com/dinedal/textql
	imports github.com/mattn/go-sqlite3
	imports os/user: unrecognized import path "os/user"
package github.com/dinedal/textql
	imports github.com/mattn/go-sqlite3
	imports path/filepath: unrecognized import path "path/filepath"
package github.com/dinedal/textql
	imports github.com/mattn/go-sqlite3
	imports regexp: unrecognized import path "regexp"
package github.com/dinedal/textql
	imports github.com/mattn/go-sqlite3
	imports strconv: unrecognized import path "strconv"
package github.com/dinedal/textql
	imports github.com/mattn/go-sqlite3
	imports unicode/utf8: unrecognized import path "unicode/utf8"

**Comment by dinedal** [comment]
An easier install method for OS X has been completed, `brew install textql`
