### ISSUE TITLE
Infer `NUMERIC` type

### ISSUE THREAD

**Issue by ivotron** [dinedal/textql#42]
It'd be nice to have an option that instructs `textql` to scan the first row and treat any unquoted number character as a `NUMERIC` data type. For the example in the demo:

```csv
id,name,value
1,Paul,5
2,Jeff,16
3,Dimitri,-3
```

Invoking with a `-infer-numeric` option would generate the following create statement:

```sql
CREATE TABLE IF NOT EXISTS tbl (
   id NUMERIC,
   name TEXT,
   value NUMERIC
)
```

This would allow executing functions such as `SUM` without having to cast columns.

**Comment by dinedal** [comment]
Yeah, this is a part of v2: https://github.com/dinedal/textql/blob/feature/v2/storage/sqlite.go#L115

I'm sorry I haven't released this yet, still on-going is the documentation and more testing. I am feature complete on v2 however, so please feel free to check it out.

**Comment by dinedal** [comment]
Also, per SQLite, https://www.sqlite.org/datatype3.html NUMERIC is a much more generic type and will change itself to TEXT in the case of non-numeric values. This provides a very flexible solution for adhoc querying.

**Comment by ivotron** [comment]
Just realized about this type affinity feature of sqlite (really cool!). I
should have looked at other branches before opening this issue :(

For completeness, I'll push the small change. Please feel free to ignore it
(I'll pull from my fork until you release v2)

**Comment by dinedal** [comment]
> I should have looked at other branches before opening this issue :(

Don't feel bad, I should be releasing a lot more often, haha! Thank you very much for looking at Textql, it's a good feeling to know people still are :)

**Comment by dinedal** [comment]
V2 is now released, and should resolve this. Please reopen if you have any issues.
