### ISSUE TITLE
cc: warning: argument unused during compilation: '-pthread' 

### ISSUE THREAD

**Issue by jungle-boogie** [dinedal/textql#48]
Hello,

Trying from your latest release:

     % go get -u github.com/dinedal/textql/...
    # github.com/mattn/go-sqlite3
    cc: warning: argument unused during compilation: '-pthread' 

What's this mean to you?

**Comment by dinedal** [comment]
Looks like you used clang to compile go-sqlite3

This is probably not an issue.

Might be of some help to you: http://stackoverflow.com/questions/13238511/xcode-clang-clang-warning-argument-unused-during-compilation-fcheck-new

**Comment by jungle-boogie** [comment]
Hi @dinedal,

Thanks for the reply.

In my gopath, the binary is called `cmd`. Is that correct?

**Comment by dinedal** [comment]
Err, sorry about that. :) fixing it

**Comment by jungle-boogie** [comment]
>Err, sorry about that. :) fixing it 

Thanks!

can you post a message when its corrected?

**Comment by dinedal** [comment]
Can you attempt it now?

**Comment by jungle-boogie** [comment]
Good now but what's causing this:

    % textql -version
            [blank]

**Comment by dinedal** [comment]
You built from source, that's expected :)

If you download a release and `make` from there you get a build that's the version

Sorry, but go doesn't really support versioning with go get...

**Comment by jungle-boogie** [comment]
> Sorry, but go doesn't really support versioning with go get...

I can do it with https://github.com/mholt/caddy but maybe he did something different.

At any rate, thanks for the new release and correcting the issue so quickly.

Thanks! :+1:

**Comment by dinedal** [comment]
He has the version as a constant in the source. It's a trade off :) There's no good way for anyone to know if a caddy version is 0.8 from source or 0.8 as released.

I might change over though, later, and it would fix it.

**Comment by jungle-boogie** [comment]
okay, got it. Thanks for your expert eyes into this matter!
