### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by joeblew99** [dinedal/textql#51]
This looks mighty useful.
I have a project with lots of CSV incoming that I need to convert to golang struts.

Are you thinking of making some examples ?
Or maybe you know of other github projects that used this ?
Oh and can it run as a lib ?

**Comment by dinedal** [comment]
> Oh and can it run as a lib ?

Yes.

> I have a project with lots of CSV incoming that I need to convert to golang struts.

Create a [NewCSVInput](https://github.com/dinedal/textql/blob/master/inputs/csv.go#L36) and if you want you can call [ReadRecord](https://github.com/dinedal/textql/blob/master/inputs/csv.go#L83) on it until it is exhausted. That'll get you a lot of rows represented as `[]string`. But if you want golang structs, instead create a  [NewSQLite3StorageWithDefaults](https://github.com/dinedal/textql/blob/master/storage/sqlite.go#L46) and then load in the rows with [LoadInput](https://github.com/dinedal/textql/blob/master/storage/sqlite.go#L80). 

Then call [ExecuteSQLString](https://github.com/dinedal/textql/blob/master/storage/sqlite.go#L198) with a "*" and `scan` into your struct.


Something like this:

```go
package main

import (
	"fmt"

	"github.com/dinedal/textql/inputs"
	"github.com/dinedal/textql/storage"
	"github.com/dinedal/textql/util"
)

type SomeData struct {
	Id   int
	Name string
}

// ./data.csv contents
/*
id,name
1,John
2,Jacob
3,Jingleheimer
4,schmidt
*/

func main() {
	opts := &inputs.CSVInputOptions{true, ',', util.OpenFileOrStdDev("./data.csv", false)}
	csvInput, _ := inputs.NewCSVInput(opts)
	storage := storage.NewSQLite3StorageWithDefaults()
	storage.LoadInput(csvInput)
	rows := storage.ExecuteSQLString("*")

	resultStructs := []SomeData{}

	for rows.Next() {
		var r SomeData
		rows.Scan(&r.Id, &r.Name)
		resultStructs = append(resultStructs, r)
	}
	// resultStructs is now an array of structs
	fmt.Println(resultStructs)
    //output: [{1 John} {2 Jacob} {3 Jingleheimer} {4 schmidt}]
}
```

**Comment by joeblew99** [comment]
Thanks !!

**Comment by goofle** [comment]
Dude, please add some examples, for God sake! I have know idea how to use this package and yet I'm desperate to use it.

By far this code snippet was the only thing I could find in terms of its usage inside code. :/
