### ISSUE TITLE
build from source failed

### ISSUE THREAD

**Issue by alagerald** [dinedal/textql#52]
Hi,

I tried to build textql on Ubuntu 14.04 64bit:

$go get -u github.com/dinedal/textql/...

# github.com/mattn/go-sqlite3
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte

Not sure why it failed. Can anyone help?

Thanks,
Gerald

**Comment by jungle-boogie** [comment]
> Not sure why it failed. Can anyone help?

built fine for me. I suggest giving more info about your system, your go and you gopath.

Can you build any other go app/utility from source?

**Comment by dinedal** [comment]
Yes, please post your Go version, and if the tests pass in your Go install.

Also, per your own output, what failed to build was actually https://github.com/mattn/go-sqlite3 and not textql.

Closing since this isn't a problem with textql, but please respond and I will try to help you figure it out.

**Comment by alagerald** [comment]
Found the problem:
The golang version is 1.2.1 which caused the problem.
Removed 1.2 and installed golang 1.4. Now it works.

Thanks a lot!
