### ISSUE TITLE
no such function: stddev

### ISSUE THREAD

**Issue by tub78** [dinedal/textql#54]
Can you help me understand why the following code does not work?

```
textql -header -output-header -sql "avg(Pct) as avg_pct" ALL_RNA_QC.csv
textql -header -output-header -sql "stddev(Pct) as stddev_pct" ALL_RNA_QC.csv
```

Here's the output

```
avg_pct
85.15
2016/02/02 12:02:28 no such function: stddev
```

**Comment by dinedal** [comment]
stddev() is not a part of the standard sqlite package. (source: https://www.sqlite.org/contrib?orderby=date )

I could probably add it, however, so will leave this open as a feature request

**Comment by tub78** [comment]
Ok.  I got my hopes up based on lines 805-808 from ast.go ...

```
805		"std":          true,
806		"stddev_pop":   true,
807		"stddev_samp":  true,
808		"stddev":       true,
```

**Comment by dinedal** [comment]
No, that means that if https://github.com/mattn/go-sqlite3 supported it out of the box it would work, but it doesn't

**Comment by tub78** [comment]
Do you recommend looking into "extension-functions.c" (50.96 KB) contributed by Liam Healy from the webpage that you referenced?

**Comment by tub78** [comment]
Love this tool, btw!

**Comment by dinedal** [comment]
Well, if you wanted to add it, we would need a version of https://github.com/mattn/go-sqlite3 that loads that file and builds it into it's output, then we can build textql against that.

Alternatively, if you are lazy; here is the SQLLite code for stddev 

```sql
SELECT AVG((t.row - sub.a) * (t.row - sub.a)) as var from t, 
    (SELECT AVG(row) AS a FROM t) AS sub;
```

(source: http://stackoverflow.com/a/4621268/164980 )

**Comment by dinedal** [comment]
> Love this tool, btw!

Thanks, I hope it does help people :)
