### ISSUE TITLE
query csv files without header

### ISSUE THREAD

**Issue by kindlychung** [dinedal/textql#55]
How do you query a csv file without header? Ideally, something like this would be nice:

```
textql -sql "$1, $2 where $2 > 100" data.csv
```

**Comment by kindlychung** [comment]
After searching the code a bit, I realized that you use c0, c1, c2... by default. Probably would be a good idea to say something about it in the readme.

**Comment by kindlychung** [comment]
Thanks for your nice work, by the way, very useful!

**Comment by dinedal** [comment]
Hey, sorry that you had some trouble. Glad you were able to figure it out.

I like your proposal in #56 so I want to make this apart of that work, and will close this issue.

**Comment by serussell** [comment]
@kindlychung What was the answer, BTW?  Can you post a sample query?

**Comment by dinedal** [comment]
```bash
textql -sql "c0, c1 where c1 > 100" data.csv
```
