### ISSUE TITLE
Support SQL UPDATE queries

### ISSUE THREAD

**Issue by hhp21** [dinedal/textql#60]
This tool is incredibly useful to me as I have to deal with very large csv files which Excel really struggles with. One use case I have sometimes is that I want to map some values in the file. Right now I would have to write something like:

`SELECT col_a, col_b, col_c, CASE WHEN col_d = 'foo' THEN 'bar' WHEN ... END col_d,  col_e, col_f, col... FROM mycsv `

It would be so useful if I could just write it as an update query:

`UPDATE mycsv SET col_d = CASE WHEN col_d = 'foo' .... END`

The output should just be dumping the updated table to stdout or the specified output file.

**Comment by dinedal** [comment]
This should work, just add a `SELECT` after your `UPDATE`, and redirect to whatever file you want to output to.

Ex: `UPDATE mycsv SET col_d = 'foo' END; *`

**Comment by hhp21** [comment]
Wow indeed that works! Awesome, thanks!
