### ISSUE TITLE
[GOOS=windows GOARCH=386 CGO_ENABLED=1] Linux host

### ISSUE THREAD

**Issue by saz59** [dinedal/textql#64]
Start on Windows - 
GetFileInformationByHandle /dev/stdin: The handle is invalid.

**Comment by dinedal** [comment]
To confirm, you're building on linux, running on windows?

**Comment by saz59** [comment]
Yes. You are right.

**Comment by dinedal** [comment]
Sorry, gonna be pretty hard to re-produce w/o a windows machine to run on.

Can you post any additional logs, trace, or is that the only message you get?

**Comment by itsnotvalid** [comment]
Hello, I use `mingw-x64` to build on windows and it fails with the same error. It only partially work when used with the bash shell accompanied by `wingw-x64` (MSYS2). Could this be related to https://github.com/golang/go/issues/14853 ? 

env;
```
go version go1.7.4 windows/amd64
gcc.exe (Rev1, Built by MSYS2 project) 6.1.0
```
