### ISSUE TITLE
May you release a prebuilt binary for windows (EXE)?

### ISSUE THREAD

**Issue by Aminadav** [dinedal/textql#65]
Thanks

**Comment by tomByrer** [comment]
Should be able to build from source; GoLang compiling is reasonably fast.
https://github.com/dinedal/textql#install

**Comment by Aminadav** [comment]
I'm trying for long time, and not success:

1.
```
C:\Go\src\github.com\dinedal\textql>go get -u github.com/dinedal/textql/..
package github.com/dinedal: directory "C:\\Go\\src\\github.com\\dinedal" is not using a known version control system
```
2.
```
C:\Go\src\github.com\dinedal\textql>go get -u github.com/dinedal/textql
package github.com/dinedal/textql: no buildable Go source files in C:\Go\src\github.com\dinedal\textql
```
3.
```
C:\Go\src\github.com\dinedal\textql>go build textql\main.go
# github.com/mattn/go-sqlite3
exec: "gcc": executable file not found in %PATH%

C:\Go\src\github.com\dinedal\textql>
```

**Comment by Aminadav** [comment]
I have try to use GCC from MinGW, but still not working:

```
C:\Go\src\github.com\dinedal\textql>go build textql\main.go
# github.com/mattn/go-sqlite3
cc1: sorry, unimplemented: 64-bit mode not compiled in
```

**Comment by Aminadav** [comment]
I have tried after download cygwin, or MinGW32 & MinGW64 and it never works.

```
C:\Go\src\github.com\dinedal\textql>go build textql\main.go
go build github.com/mattn/go-sqlite3: C:\Go\pkg\tool\windows_amd64\cgo.exe: exit status 2
```

Some may please build it and give everyone the EXE file of it?

Thanks.

**Comment by gen1us** [comment]
https://www.dropbox.com/s/ylcxdozu8efdhdj/textql.exe?dl=1

**Comment by dinedal** [comment]
I would strongly advise against downloading random exes

**Comment by tlehman** [comment]
@dinedal @Aminadav We could make a windows package for the [Chocolatey package manager](https://github.com/chocolatey/choco/wiki/CreatePackages), sound good?

**Comment by dinedal** [comment]
@tlehman Go for it

**Comment by Aminadav** [comment]
Why require the users install Chocolately? it's much easier if you upload
the binary to GitHub releases page.

**Comment by dinedal** [comment]
@Aminadav agreed, I need to spin up a windows VM someplace to build it, just haven't had the time.

**Comment by tlehman** [comment]
I have a Windows 10 machine at home, I'll do it when I have some time

**Comment by Aminadav** [comment]
You can register for a free trial of a cloud service. For example, Google
gives you a free $300 credit.
Then you make the windows environment you need. Afer the build complete you
can pause the machine.
This way the $300 it's enough funds for a long time because you're going to
use the credits only while the machine is on, and the building is in
process.

​Thanks!​



*Aminadav Glickshtein,*Freelancer, Software Developer
<https://www.toptal.com/resume/amindav-glickshtein#explore-only-top-flight-freelancers-now>
<https://www.facebook.com/aminadav.gl/>  <http://linkedin.com/in/aminadavg>
<http://twitter.com/AminadavG>
<http://www.youtube.com/channel/UCCQxUMzjB3m9jA3uObx3vLg>
<http://angel.co/aminadav-glickshtein>
<http://stackoverflow.com/users/1229624/aminadav>
<http://github.com/aminadav>

**Comment by elvarb** [comment]
I tested a build on my Windows machine, the build finished fine but trying to parse a basic and simple csv file always results in 

   2018/04/13 14:08:07 unrecognized token: ":"

There is no : in the csv, or in the command I'm giving it

    .\textql.exe -sql "select count(*)" .\test.csv

**Comment by vovcacik** [comment]
@Aminadav I went through the same errors as you but the `cgo.exe: exit status 2`. I got it working with golang+mingw64. Did you install it through WinBuilds, if so see this [report](https://stackoverflow.com/questions/43396453/golang-cgo-exit-status-2-on-windows)? I used vanilla build `x86_64-7.3.0-release-win32-seh-rt_v5-rev0.7z`.

**Comment by vovcacik** [comment]
@elvarb that issue is caused by #79 and related to #80.

**Comment by vovcacik** [comment]
@dinedal since the Windows build isn't without caveats I figured out this could be handy:

```batch
@echo off
setlocal

:: Automated build of github.com/dinedal/textql
:: - assumes wget, 7za and git on PATH
:: - "installs" golang and mingw64 (actually only unpacks local copy)

:: Dependencies
set GO_ARCHIVE=go1.10.1.windows-amd64.zip
set MINGW_ARCHIVE=x86_64-7.3.0-release-win32-seh-rt_v5-rev0.7z

wget --no-check-certificate "https://dl.google.com/go/%GO_ARCHIVE%"
wget --no-check-certificate "https://netix.dl.sourceforge.net/project/mingw-w64/Toolchains targetting Win64/Personal Builds/mingw-builds/7.3.0/threads-win32/seh/%MINGW_ARCHIVE%"

7za x %GO_ARCHIVE%
7za x %MINGW_ARCHIVE%

pushd "go\bin"
set PATH=%PATH%;%CD%
popd

pushd "mingw64\bin"
set PATH=%PATH%;%CD%
popd

:: Build
go get -u github.com/dinedal/textql/...

```

Give it a spin @Aminadav

**Comment by elvarb** [comment]
@vovcacik that workaround works

.\textql.exe -header -sql "select * from [C:\Textql\borholur2413112015] limit 3" C:\Textql\borholur2413112015.csv

the escaped part is just the file location minus the file extension

**Comment by tsundara** [comment]
Hi, please release Linux and Windows binaries. Setting up Go environment and building from source is just too much work or impossible for people who are in restricted environments (admin privilege issues / proxy issues). Also"go get" needs "git" installed, and it is a pain to install git in restricted environments. There is too much friction.

**Comment by amuc2** [comment]
https://github.com/dinedal/textql/issues/113

https://github.com/dinedal/textql/issues/65
https://github.com/dinedal/textql/issues/87

**Comment by amuc2** [comment]
https://github.com/mattn/go-sqlite3/issues/467

**Comment by amuc** [comment]
This worked for me:

~~~
go get -v github.com/dinedal/textql/...
~~~

https://musl.cc/x86_64-w64-mingw32-native.zip

**Comment by Aminadav** [comment]
I'm leaving. Thanks to you. Now I have Mac.
