### ISSUE TITLE
hyphen in filename causes syntax error

### ISSUE THREAD

**Issue by mcsurly** [dinedal/textql#67]
textql -dlm=tab -header -sql "select hostname,ip order by hostname" my-nodes.txt
2017/05/30 00:35:23 near "-": syntax error
mv my-nodes.txt my_nodes.txt
textql -dlm=tab -header -sql "select hostname,ip order by hostname" my_nodes.txt
[[ expected output ]]

**Comment by dinedal** [comment]
Right now, you need to escape the `-` for this to work:

```bash
$ textql -dlm=tab -header -sql "select hostname, ip from [my-nodes] order by hostname"  ~/my-nodes.txt
remote.host,255.255.255.0
www.example.com,127.0.0.1
```

I am working on an implicit mapping that would handle this for everyone, but haven't finished yet.

**Comment by mcsurly** [comment]
Ok now I understand what you're getting at. It's not choking on the filename containing a hyphen... It's the implicitly generated TABLE name that is causing problems.
I can live with that workaround. Thanks very much!
