### ISSUE TITLE
Docker execution error

### ISSUE THREAD

**Issue by OndraTom** [dinedal/textql#89]
I'm trying to use TextQL from Dockerfile command.

Simple example:

`FROM golang:1.10`
`RUN go get -u github.com/dinedal/textql/...`
`CMD ["textql", "-sql", "SELECT 1"]`

TextQL installs properly, but the final command returns code 1 and weird error output:

`2018/04/20 14:29:53 EOF`

If I connect to the container and run TextQL from there, everything works properly.

Can you tell what is the reason why TextQL is not able to run properly from Dockerfile command? It can be executed only after container construction but not in it. That's quite impractial.

**Comment by OndraTom** [comment]
I got it. It must be connected with TTY, which is possible with -t parameter in docker run command.

**Comment by nanawel** [comment]
For anyone with the same issue with a command in the crontab, if your job ends with return code 1 without any message except:

```
2023/11/22 14:33:01 EOF
```

the "proper" workaround is to use `screen` to allocate a pseudo-tty like so:

```shell
0 0 * * * user screen -S myscreename -d -m textql...
```

Source: http://www.linta.de/~aehlig/techblog/2011-06-16.html
