### ISSUE TITLE
Alias does not work with spaces in $pwd

### ISSUE THREAD

**Issue by peterjaap** [dinedal/textql#92]
docker: invalid reference format: repository name must be lowercase.

**Comment by yuanyangwu** [comment]
not textql but docker issue

https://github.com/moby/moby/issues/36080
https://linuxacademy.com/community/posts/show/topic/24089-docker-invalid-reference-format-repository-name-must-be-lowerca

**Comment by dinedal** [comment]
Closing this as this issue is unrelated to textql; it also looks like the underlying issue is resolved too.
